CREATE TABLE `BankTransactions` (
	`transaction_id` text NOT NULL,
	`user_id` integer NOT NULL,
	`bank_id` text NOT NULL,
	`account_id` text NOT NULL,
	`category_id` integer,
	`status` text NOT NULL,
	`booking_date` timestamp,
	`value_date` timestamp,
	`amount` text NOT NULL,
	`currency` text NOT NULL,
	`exchange_rate` text,
	`creditor_name` text,
	`creditor_bban` text,
	`debtor_name` text,
	`debtor_bban` text,
	`additional_information` text,
	`spending_type` text,
	`want_or_need` text,
	PRIMARY KEY(`account_id`, `transaction_id`, `user_id`),
	FOREIGN KEY (`user_id`) REFERENCES `Users`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`category_id`) REFERENCES `Categories`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`user_id`,`bank_id`,`account_id`) REFERENCES `Accounts`(`user_id`,`bank_id`,`account_id`) ON UPDATE no action ON DELETE cascade
);
